//
//  Session.swift
//  ARKitBasics
//
//  Created by Abhinav Prakash on 27/11/17.
//  Copyright © 2017 Apple. All rights reserved.
//

import UIKit
import CoreData
import SceneKit

/* Class representation of DB entity: Session. Extension for this is already
 generated by codegen in the DB*/

class Session: NSManagedObject {
    
    static func createSession(with sessionId: String, in context: NSManagedObjectContext) -> Session {
        
        let aSession = Session(context: context)
        // For testing sessionId remains a constant
        aSession.sessionId = "123456"
        return aSession
    }
    
    static func fetchSessionCount(in context: NSManagedObjectContext) {
        let request: NSFetchRequest<Session> = Session.fetchRequest()
        if let sessionCount = (try? context.fetch(request))?.count {
            print("\(sessionCount) - Count of sessions")
        }
    }
    
    static func fetchAllSessions(in context: NSManagedObjectContext) {
        let request: NSFetchRequest<Session> = Session.fetchRequest()
        if let sessions = (try? context.fetch(request)) {
            for session in sessions {
                print("\(session.sessionId!) - session")
            }
        }
    }
    
    static func deleteAllSessions(in context: NSManagedObjectContext) {
        let request: NSFetchRequest<Session> = Session.fetchRequest()
        if let sessions = (try? context.fetch(request)) {
            for session in sessions {
                context.delete(session)
                try? context.save()
            }
        }
    }
}
